### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by losyme** [oliwer/mango#28]
Hello,

This code produce an error and I don't know why ?
```
use strict;
use warnings;
use feature qw(state say);
use EV;
use AnyEvent;
use Mango;

sub mango { state $m = Mango->new('mongodb://quag:quag@192.168.1.44:27017/admin') }
my $cv = AE::cv;

mango->db('Quag')->command(buildInfo => sub {
    my ($db, $err, $doc) = @_;
    $cv->send($doc->{version});
});
say $cv->recv;

```
**Mojo::Reactor::EV: I/O watcher failed: Mojo::IOLoop already running at /opt/perl5/perls/perl-5.26.1/lib/site_perl/5.26.1/Mango/Auth/SCRAM.pm line 66.**
3.2.11

Without MongoDB auth, no error.

**Comment by michaelfung** [comment]
I have the same issue.

I use Mango with Mojolicious. Excerpt:

`$app->helper( 'mango' => sub { state $m = Mango->new($mongo_url) } );`

And in a callback:

```
my $hubs_coll = $app->mango->db('wfh')->collection('hubs');
my $doc; $doc = $hubs_coll->find_one({hub_id => $c->stash('req_json')->{username}});
...
```

Things still work in spite of the warning.

**Comment by losyme** [comment]
https://github.com/INA-SLAN-ADMINS/mango

**Comment by michaelfung** [comment]
@losyme , Many thanks! I will try your patches.

**Comment by oliwer** [comment]
This issue should be fixed in release 1.30. Sorry for the delay.
@losyme where did your repo go? Feel free to submit patches ;)

**Comment by michaelfung** [comment]
@oliwer , just in case you missed it, from @losyme:

```
## lib/Mango/Collection.pm

@@ -71,7 +71,12 @@ sub find {
  sub find_and_modify {
    my ($self, $opts) = (shift, shift);
    return $self->_command(bson_doc(findAndModify => $self->name, %$opts),
 -    shift, sub { shift->{value} });
 +    shift,
 +    sub {
 +      my $doc = shift;
 +      return $doc ? $doc->{value} : undef;
 +    }
 +  );
  }

  sub find_one {

```

And many thanks for everyone's effort!

**Comment by oliwer** [comment]
Thanks. I'm adding it too.
